### PR TITLE
linux checklist scripts

### PR DESCRIPTION
**Pull request by minsooerickim**
yea so.. i'm not sure if this is what u expected

### CODE REVIEW

**Comment by AnthonyH45** [comment]
I like the general idea, but quick question

Is this supposed to be ran as a script or is it just a txt file with some commands to reference?

**Comment by minsooerickim** [comment]
> I like the general idea, but quick question
> 
> Is this supposed to be ran as a script or is it just a txt file with some commands to reference?



> I like the general idea, but quick question
> 
> Is this supposed to be ran as a script or is it just a txt file with some commands to reference?

they are supposed to be ran as a script. I just put them all into one .txt file.

**Comment by minsooerickim** [comment]
i looked back at my files and ig its kind of a combination of both commands to remmber and scripts 😂, but I meant to write scripts

**Comment by AnthonyH45** [comment]
It wont run for a few reasons, I'll go ahead and merge it as a reference since we can still use the info, just need to type by hand. I can work with you on discord to fix some things

**Pull request merged**
